### PR TITLE
Update sentry to v7

### PR DESCRIPTION
**Pull request by wilco375**
Updates Sentry to v7. We can no longer use Sprockets to include Sentry because the node package no longer includes a compiled file.

### CODE REVIEW

**Comment by guidojw** [comment]
Did you read the v7 changelog? https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#700 
There's some stuff about 'bundle.min.js' that seems relevant

**Comment by wilco375** [comment]
> Did you read the v7 changelog? https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#700 There's some stuff about 'bundle.min.js' that seems relevant
That's about the bundles for CDNs. But the NPM package seems to no longer include a bundle at all, looking at the files in `node_modules/@sentry/browser`

**Review by guidojw — APPROVED** [review]

**Review by guidojw — CHANGES_REQUESTED** [review]
Actually, shouldn't we use this official looking way? https://docs.sentry.io/platforms/javascript/guides/vue/

**Comment by wilco375** [comment]
> Actually, shouldn't we use this official looking way? https://docs.sentry.io/platforms/javascript/guides/vue/

We have a bit of a weird setup; Vue is not used/included on every page, only on some with dynamic content.

**Review by guidojw — APPROVED** [review]

**Pull request merged**
