### PR TITLE
Add pagination to activity and credit_mutation index page

### PR DESCRIPTION
**Pull request by Matthijsy**
Currently, we show all information of all old activities and credit mutations. Those are probably not that interesting. So they are removed from the index page. They are still accessible, so via a user page or another link they are still accessible.

### CODE REVIEW

**Comment by wilco375** [comment]
Is this really a problem? The only person who can see the really old activities is the treasurer, because bartenders only see the activities that are not locked yet. And as a treasurer I do find myself going back to old activities of for example last year sometimes.

**Comment by wilco375** [comment]
It would be nice to implement pagination though, but that requires quite a bit more work to implement

**Comment by Matthijsy** [comment]
It is indeed only a 'issue' for the treasurer. The only issue is the fact that it loads slow for the treasurer which I did not like. For what do you need the old activities? Pagination would be nice but might be a bit overkill

**Comment by Matthijsy** [comment]
Okay pagination wasn't that hard..

Screenshot_2020-05-29_09-51-08
(for this screenshot I lowerd the items per page to 2, but by default it is 25)

**Comment by wilco375** [comment]
Haha, nice

Op vr 29 mei 2020 om 09:51 schreef Matthijs Vos <notifications@github.com>:

**Pull request merged**
