### PR TITLE
Fix flash message for pin

### PR DESCRIPTION
**Pull request by wilco375**
After the flash notifications were fixed, I noticed that they did not account for pin transactions yet. This PR fixes that.

### CODE REVIEW

**Comment by guidojw** [comment]
It looks like now it'll almost never show the user name anymore, is this desirable?

**Comment by wilco375** [comment]
> It looks like now it'll almost never show the user name anymore, is this desirable?

This is not the case. A user always orders on credit, i.e. paid_with_cash and _pin are always false for users. Only external people that are not in the user list can pay by pin or cash.

**Comment by DrumsnChocolate** [comment]
I feel like the condition could have been changed into something more like this:
```ruby
let additionalInfo = `${user ? user.name : (response.body.paid_with_pin ? 'Pin' : 'Contant'} - ${orderTotal}`;
```
@guidojw maybe this makes more sense to you, because it's more similar to the previous condition, but I think this does the same thing as the new code. That is, if there is a user, then that means no payment has been made with pin or cash. (@wilco375 can you confirm this?)

**Comment by wilco375** [comment]
> I feel like the condition could have been changed into something more like this:
> 
> ```ruby
> let additionalInfo = `${user ? user.name : (response.body.paid_with_pin ? 'Pin' : 'Contant')} - ${orderTotal}`;
> ```
> 
> @guidojw maybe this makes more sense to you, because it's more similar to the previous condition, but I think this does the same thing as the new code. That is, if there is a user, then that means no payment has been made with pin or cash. (@wilco375 can you confirm this?)

I felt that two ternary operators did wasn't great for readability so I changed it to an if statement. But if others feel different about this, I can also update it.

**Comment by DrumsnChocolate** [comment]
No I just wrote it in a different way for @guidojw but I see that you commented on the matter just before I replied

**Review by DrumsnChocolate — APPROVED** [review]

**Pull request merged**
