### PR TITLE
Feature/invoice

### PR DESCRIPTION
**Pull request by Matthijsy**
This PR is the first step for automatic invoicing. My final idea is to have an automated system (from end of the drink to payment done) for invoicing (drinks on 'external' account excluded, since we do not know the mailadres for that one).

This PR is the first step. You can create an invoice based on an activity and user. This can the be send to that user. 

What it does:
- Invoice object creation
- PDF generation

What it does not (will be done in follow up PR's)
- Automatic invoice creation when drink gets locked
- Support for custom invoice entries (like 'tappersloon' and rent)
- Support for custom mailadres (for the external account)
- Probably some more stuff

### CODE REVIEW

**Comment by wilco375** [comment]
image
The date in the activity searchbox is shown in English/American instead of Dutch

**Comment by wilco375** [comment]
image
And on the invoice the date in the text is also in English. And the date separator on the invoice date should be '-' instead of '/'

**Comment by wilco375** [comment]
image
Also the product prices aren't very nicely formatted yet

**Comment by wilco375** [comment]
And if I click on the Send PDF button I get this error: 
`PDF could not be generated!
 Command Error: /var/lib/gems/2.5.0/gems/wkhtmltopdf-binary-0.12.5.4/bin/wkhtmltopdf:39:in `initialize': Permission denied @ rb_sysopen`

**Comment by wilco375** [comment]
Other than that it looks really nice for a first version

**Comment by Matthijsy** [comment]
> Command Error: /var/lib/gems/2.5.0/gems/wkhtmltopdf-binary-0.12.5.4/bin/wkhtmltopdf:39:in 'initialize': Permission denied @ rb_sysopen

You should chmod this directory, see https://github.com/zakird/wkhtmltopdf_binary_gem#installation-and-usage

**Comment by wilco375** [comment]
- The date now shows as `01-apr-20` which is also quite a weird format in my opinion. I always just put it in human-readable format there, so `1 april 2020`
- The phone number on the invoice is not my phone number
- It would be nice to see if a PDF is sent yet or not. If I click the button to send the invoice and refresh the page I have no way of knowing if I already sent it or not. Maybe remove the button altogether after clicking it, or at least show an indication somewhere that it was already sent.
- The generated PDF seems to be lacking some markup and having the wrong encoding:
image

**Comment by Matthijsy** [comment]
@wilco375 If you have time could you give this another review round?

**Review by wilco375 — APPROVED** [review]

**Pull request merged**
