### PR TITLE
feat(tests): add code coverage reporting

### PR DESCRIPTION
**Pull request by guidojw**
### Summary

Adds code coverage reporting with [Codecov](https://about.codecov.io/).

requires https://github.com/csvalpha/sofia/pull/945

### CODE REVIEW

**Comment by lodewiges** [comment]
this first needs a fix similair to amber-api 
https://github.com/csvalpha/amber-api/pull/441
https://github.com/csvalpha/amber-api/pull/444

**Comment by guidojw** [comment]
@lodewiges fixed

**Comment by lodewiges** [comment]
This doesnt fixes it if i am correct

**Comment by guidojw** [comment]
It does fix it, I missed some changes copying it from the other similar prs before but it should be good now

**Pull request merged**
