### PR TITLE
Implement sumup button in order screen

### PR DESCRIPTION
**Pull request by Matthijsy**
This PR creates a button which automatically redirects to the Sumup app. This button is only visible on mobile devices. This makes the checkout procedure when using pin much easier. We can then use a table which runs the sumup app and use this for faster pin payments.

### CODE REVIEW

**Comment by wilco375** [comment]
Maybe we should first make the order screen a bit more mobile friendly...

**Comment by Matthijsy** [comment]
For a real mobile this is true, but if we use a tablet this is not a problem right?

**Comment by wilco375** [comment]
Other than that, nice :)

**Comment by wilco375** [comment]
> For a real mobile this is true, but if we use a tablet this is not a problem right?

Is that also detected as being a mobile device? Is it based on the User-Agent?

**Comment by Matthijsy** [comment]
Yes, it is based on UA, we should still add tablet (since apparently that is not a mobile device) but then it would be available on tablet as well. 

https://github.com/csvalpha/sofia/pull/459/files#diff-5972b647f754a2fc2857a16dc3628cd9R97
https://github.com/fnando/browser/blob/master/lib/browser/device.rb#L82

**Pull request merged**
