### PR TITLE
feat(renovate.json): add regex manager for updating Sentry SDK

### PR DESCRIPTION
**Pull request by guidojw**
### Summary

Created this custom regex manager to update the Sentry SDK after my findings in #797 that Sentry doesn't publish bundles to cdnjs anymore.

### CODE REVIEW

**Comment by guidojw** [comment]
Also added a custom changelog URL to Renovate animate.css PRs because I saw that #803 has no changelog entries included.

**Comment by wilco375** [comment]
> Also added a custom changelog URL to Renovate animate.css PRs because I saw that #803 has no changelog entries included.



> Also added a custom changelog URL to Renovate animate.css PRs because I saw that #803 has no changelog entries included.

Isn't this because there is no changelog in the repo? Clicking the 'source' link in #803 also redirects to the repo you added in the config here

**Comment by guidojw** [comment]
> > Also added a custom changelog URL to Renovate animate.css PRs because I saw that #803 has no changelog entries included.
> 
> Isn't this because there is no changelog in the repo? Clicking the 'source' link in #803 also redirects to the repo you added in the config here
> 
> I think there are many deps without a changelog, see e.g. #786

Renovate fetches the GitHub releases information as changelog, animate.css has this https://github.com/animate-css/animate.css/releases
But yeah it looks like Renovate already knows about `animate.css`'s GitHub repository, so something else is going on here, I'll revert those changes.

Relevant Renovate logs:
```
DEBUG: Fetching changelog: https://github.com/daneden/animate.css (3.5.2 -> 4.1.1)(branch="renovate/animate.css-4.x")
DEBUG: Not enough valid releases for dep animate.css(branch="renovate/animate.css-4.x")
```

**Review by wilco375 — APPROVED** [review]
Renovate is pretty cool! Their documentation could be better though 😅

**Pull request merged**
